import { FlatCompat } from "@eslint/eslintrc";
import { fileURLToPath } from "node:url";
import { dirname } from "node:path";

// eslint-config-next (15.5.23) still ships an `extends`-based config, not a
// native ESLint 9 flat config — FlatCompat is Next.js's own documented
// bridge for this (https://nextjs.org/docs/app/api-reference/config/eslint),
// not a workaround specific to this repo.
const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  // next-env.d.ts is regenerated by Next.js on every build and isn't meant
  // to be hand-edited — same reasoning as .next/** and node_modules/**.
  { ignores: [".next/**", "node_modules/**", "next-env.d.ts"] },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default config;
